export const USER = {
    USER_DATA: "USER_DATA",
};

export const Chatting = {
    SOCKET: "CHATTING_SOCKET",
    UNREAD: "CHATTING_UNREAD_MESSAGE",
    UNREAD_SELECTOR: "CHATTING_UNREAD_MESSAGE_SELECTOR",
    SELECTED_ROOMID: "CHATTING_SELECTED_ROOMID",
};

export const SELECTED_DAY = {
    SELETED_DAY_DATA: "SELETED_DAY_DATA",
};
