@url = http://localhost:3002/api
@access = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoidGVzdDQiLCJpYXQiOjE2NzUyNzk4NzEsImV4cCI6MTY3NTI4MTY3MX0.8h_ZBLvtzsc-tOI8Cz293AZbnJ0HNf3-XelGlF0krOk
@refresh = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiIiwiaWF0IjoxNjc1Mjc5ODcyLCJleHAiOjE2NzUyOTA2NzJ9.3EKxcUSueY1W7G8VlbnS4uRc097Gym-K5BXHU_E3zS4

#############################3#토큰 발급용 로그인,로그아웃##########################
###login
POST {{url}}/account/login
Content-Type: application/json

{
    "userID": "test4",
    "password": "test4"
}
###logout
delete {{url}}/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoicnV5cmlhIiwiaWF0IjoxNjcwODI1NTEzLCJleHAiOjE2NzA4MjczMTN9.bF7IQhHtU1kx8-LawnSHIXitx71sJxNYqbsQ3a-HXLg
RefreshToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiIiwiaWF0IjoxNjcwODI1NTE1LCJleHAiOjE2NzA4MzYzMTV9.CPLRfDOPsDt3r9dGmlCjlRBWEFrunR_n-YDIh2D5ATM
Content-Type: application/json


###이메일 인증번호 발신 API
post {{url}}/users/findid
Content-Type: application/json

{
  "email":"ehlee7003@gmail.com"
}


###회원가입
post {{url}}/users/new
Content-Type: application/json

{
  "userID": "euiho",
  "password": "0000",
  "email":"ehlee7003@gmail.com",
  "nickname":"euiho",
  "emailVerification":"0"
}


##################################################################################

### 일기 작성 api
post {{url}}/diaries
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}
Content-Type: application/json

{
  "title": "진짜 일기에용",
  "description":"진짜 일기라니까용",
  "weather": "cloudy",
  "lock":false,
}

### 유저가 쓴 일기를 달 단위로 조회
get {{url}}/diaries/user/?year=2023&month=2
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}

### 모든 일기 조회
get {{url}}/diaries/all?user=false&count=10&page=2&emotion=all&lock=false
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}

### 특정 일기 조회
get {{url}}/diaries/18
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}

### 일주일 / 한달 / 일년 전 일기 조회
get {{url}}/diaries/period/all
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}

### 일기 수정
PATCH  {{url}}/diaries/2
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}
Content-Type: application/json

{
  "title": "수정했어용",
  "description":"수정했어용!!!",
  "weather": "cloudy",
  "emotion": "sad",
  "lock": true
}

### 일기 삭제
delete {{url}}/diaries/11
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}

### 공감 증가
put {{url}}/diaries/3/likes
Authorization: Bearer {{access}}
RefreshToken: {{refresh}}
Content-Type: application/json

{
  "amount": -1
}